### ISSUE TITLE
Unable to select audio devices or webcam

### ISSUE THREAD

**Issue by midget3111** [trigg/Rebuttal-Client#26]
I can select an Output Device fine, but neither input displays anything other than "Any"

Errors include "Uncaught (in promise) DOMException: The element has no supported sources." 

And 

"error:NotReadableError: Could not start audio source"

**Comment by trigg** [comment]
This should only be happening if it fails to find any source :

- No audio device available
- Permission has been denied / not yet been accepted

**Comment by midget3111** [comment]
> This should only be happening if it fails to find any source :
> 
>     * No audio device available
> 
>     * Permission has been denied / not yet been accepted

This is using a fresh install of the Electron app, so perms shouldn't be too much of an issue?
Let me check my sound settings.

**Comment by midget3111** [comment]
After looking into this, I'm fairly sure it's my Pipewire setup being dodgy.

**Comment by midget3111** [comment]
Okay, this is now fixed for Rebuttal-Client. Still having the same issue on Rebuttal-Webchat.
