### ISSUE TITLE
Save server info on client

### ISSUE THREAD

**Issue by midget3111** [trigg/Rebuttal-Client#28]
Currently you have to enter email address and password manually each time. 
This is a faff which costs me valuable seconds.

**Comment by trigg** [comment]
This should be working, I'll look into it again

**Comment by trigg** [comment]
If libsecret and gnome-keyring are installed the user's name(list) should appear below each server, clicking on the name will log in as that user.

**Comment by midget3111** [comment]
For anyone else who may be confused, click on your email address to auto login
